config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :items
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items, through: :categorizations
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  belongs_to :item
  belongs_to :owner, class_name :users
  belongs_to :renter, class_name :users
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :categories, through: :categorizations

  CONDITIONS = ['New', 'Like New', 'Used', 'Old', 'Damaged', 'Fair']
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  has_many :contracts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = set_item
  end

  def new
    @user = User.find(params[:user_id])
    @item = Item.new
  end

  def edit
    @item = set_item
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = params[:user_id]
    respond_to do |format|
      if @item.save
        format.html {redirect_to user_path(params[:user_id]), notice: "Item Successfully Created"}
        format.json {render :show, status: :created, location: @item}
      else
        format.html {render :new}
        format.json {render json: @item.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html {redirect_to @item, notice: "Item Successfully Saved"}
        format.json {render :show, status: :ok, location: @item}
      else
        format.html {render :edit}
        format.json {render json: @item.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html {redirect_to items_url, notice: "Item Deleted"}
      format.json {head :no_content}
    end
  end

  private

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :description, :date_purchased, :condition, :brand)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = set_user
  end

  def new
    @user = User.new
  end

  def edit
    @user = set_user
  end

  def create
    @user = User.new(user_params)
    @user.date_joined = DateTime.now
    respond_to do |format|
      if @user.save
        format.html {redirect_to @user, notice: "Info Successfully Saved"}
        format.json {render :show, status: :created, location: @user}
      else
        format.html {render :new}
        format.json {render :json, @item.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(item_params)
        format.html {redirect_to @user, notice: "Info Successfully Saved"}
        format.json {render :show, status: :ok, location: @user}
      else
        format.html {render :new}
        format.json {render :json, @item.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html {redirect_to users_path, notice: "User Account Deleted"}
      format.json {head :no_content}
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password, :name, :password, :email, :date_joined, :city, :state, :zip)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.slim
= form_for([@user, @item]) do |f|
  - if @item.errors.any?
    #error_explanation"
      h2 = "#{pluralize(@item.errors.count, "error")} prohibited this thing from being saved:"
      ul
        - @item.errors.full_messages.each do |message|
        li = message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :date_purchased
    = f.date_select :date_purchased
  .field
    = f.label :condition
    = f.select("condition", Item::CONDITIONS)
  .field
    = f.label :brand
    = f.text_field :brand
  .actions = f.submit

app/views/items/edit.html.slim
h1 Edit Gear

== render 'form'

= link_to 'Back', user_path(@user)

app/views/items/index.html.slim
h1 Your Gear
= link_to 'Add New Gear', new_item_path
table
  thead
    tr
      th Name
      th Brand
      th Condition
      th Purchase Date
  tbody
    - @items.each do |thing|
      tr
        td = thing.name
        td = thing.brand
        td = thing.condition
        td = thing.date_purchased

app/views/items/new.html.slim
h1 New Gear

== render 'form'

= link_to 'Back', user_path(@user)

app/views/items/show.html.slim
h1
  = @item.name

h4 Description
p= @item.description
h4 brand
p= @item.brand
h4 Condition
p= @item.condition

= link_to 'Back', items_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Rails Associations
    == stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    == yield

app/views/users/_form.html.slim
= form_for @user do |f|
  - @user.errors.any?
    #error_explanation"
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this thing from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
        li = message
  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :zip
    = f.text_field :zip
  .actions = f.submit

app/views/users/edit.html.slim
h1 Edit User Information

== render 'form'

= link_to 'Back', user_path

app/views/users/new.html.slim
h1 New User

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
h1 Welcome #{@user.name}
= @user.date_joined

- @user.items.each do |item|
  p = item.name

= link_to 'Add Gear', new_user_item_path(@user)
= link_to 'Home', '/'